# Generated by Django 4.2.2 on 2023-06-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0002_customgroup_custompermission_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=45)),
                ('recipient', models.CharField(max_length=45)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sms',
            },
        ),
    ]
